export const ActionTypes =  {
    LOGIN:"LOGIN",
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCTS : "SELECTED_PRODUCTS",
    REMOVE_SELECTED_PRODUCTS : "REMOVE_SELECTED_PRODUCTS",
    SEARCH_PRODUCTS : "SEARCH_PRODUCTS",
    ADD_ITEM  : "ADD_ITEM",
    REMOVE_ITEM : "REMOVE_ITEM",
    REMOVE_ITEM_CART : "REMOVE_ITEM_CART",
    FILTER_ITEM_BY_CATEGORY : "FILTER_ITEM_BY_CATEGORY",
    GET_CART_ITEM :"GET_CART_ITEM",
    SET_CART_ITEM :"SET_CART_ITEM",
    CLEAR_PRODUCT_FROM_CART:"CLEAR_PRODUCT_FROM_CART",
    PLACE_ORDER :"PLACE_ORDER"
}